### ISSUE TITLE
User object not retrieved.

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1016]
### Description

When I try running the project locally and I try registering a user, It shows an error.

### What should have happened?

I expect the registration to work successfully.

### Further details

![image](https://user-images.githubusercontent.com/67182544/133763364-70ea311b-bf73-4699-88be-04f031defece.png)
![image](https://user-images.githubusercontent.com/67182544/133763487-61446088-b524-40de-b07f-89301dbc4b11.png)

**Comment by gorkemarslan** [comment]
Unfortunately, this error is caused by my missing commit. I’ve already added a new PR #1015  to fix this issue.

I am really sorry for my lack of attention.

PS: I use PyCharm for development. I forget selecting changes at the bottom of the file before commit so I only sent ones placed on the top. This is the reason why unittests did not fail. Without the last PR, tests fails. At least our tests are working :) 
Both our program and the tests are working well without a problem.

**Comment by AbhijithGanesh** [comment]
> 
> 
> Unfortunately, this error is caused by my missing commit. I’ve already added a new PR #1015 to fix this issue.
> 
> I am really sorry for my lack of attention.
> 
> PS: I use PyCharm for development. I forget selecting changes at the bottom of the file before commit so I only sent ones placed on the top. This is the reason why unittests did not fail. Without the last PR, tests fails. At least our tests are working :)
> Both our program and the tests are working well without a problem.

Yes thank you, this issue has been fixed, I just would like to know whether you could use the AbstractUser or User model instead of the method get_user_model()

**Comment by gorkemarslan** [comment]
I'll answer your question in the related PR, in which you also asked the same question.

**Comment by AbhijithGanesh** [comment]
Yes thank you, I really appreciate the words you've taken to restructure, I can't express how good this has turned out,.
