### ISSUE TITLE
Create global API router

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1030]
We should determine how to use a common URL prefix across API endpoints when migrating the API code into separate Django apps. 

For example, perhaps the `api` app can contain one `router.py` file that defines a DRF [`SimpleRouter`](https://www.django-rest-framework.org/api-guide/routers/#usage), called `CiviWikiRouter`. 

```py
# in api/router.py
from rest_framework import routers

CiviWikiRouter = routers.SimpleRouter()
```

Then, all api-related code can use the `CiviWikiRouter` when [registering API routes](https://www.django-rest-framework.org/api-guide/routers/#usage). 

```py
# in <app>/api.py
from api.router import CiviWikiRouter

CiviWikiRouter.register(r'endpoint', SomeViewSet)
```

In order to register the `CiviWikiRouter` URLs:

```py
# In core/urls.py
from api.router import CiviWikiRouter

urlpatterns = [
    ...
    path('api/', include((CiviWikiRouter.urls, 'api'))),
]
```

**Comment by gorkemarslan** [comment]
I am up for working on this issue if no one is a volunteer.

**Comment by gorkemarslan** [comment]
@brylie, since we will remove `api` app soon, we need to find a better place for `router.py`. I think we can use `core/router.py` for this purpose. All apps can register this router which is at the core of the project: `core` app :) There is a [SO question](https://stackoverflow.com/questions/34637294/where-to-put-routers-py-for-database-routing-in-a-django-project) that supports my logic.

> I put mine in projectname/projectname/, parallel with settings.py, since I see it as a kind of setting.

You write the location for the api-related URLs to register `CiviWikiRouter` as:

`# in <app>/api.py `

Since urls.py files care to route,` api.py` is not the right location in my opinion.

If `urls` folder is present in the apps we should use

`<app>/urls.api.py`    --> You might have implied that one.  🤔 

If not, 
`<app>/urls.py`

**Comment by gorkemarslan** [comment]
My plan is this:

Creating `router.py` file in `core` app for  `CiviWikiRouter`:
```python
# in core/router.py
from rest_framework import routers

CiviWikiRouter = routers.SimpleRouter()
```

For `accounts` app, which has `urls` dir consisting of `urls.py` and `api.py`. Inside `api.py`:
```python
# in accounts/urls/api.py
from core.router import CiviWikiRouter

CiviWikiRouter.register(r'accounts', SomeViewSet)
```

The remaining apps only have urls.py. To give an example, let's consider `categories` app

```python
# in categories/urls.py
from core.router import CiviWikiRouter

CiviWikiRouter.register(r'categories', SomeViewSet)
```

To register the router:

```python
# In core/urls.py
from core.router import CiviWikiRouter

urlpatterns = [
    ...
    path('api/', include((CiviWikiRouter.urls, 'api'))),
]
```

**Comment by brylie** [comment]
Sounds good. It might be good to prefix the routes with `v1` in case we create a new version of the API:

```py
# in core/router.py
from rest_framework import routers

CiviWikiRouter = routers.SimpleRouter(prefix="v1")
```

Also, the [`DefaultRouter`](https://www.django-rest-framework.org/api-guide/routers/#defaultrouter) might be a good choice, since it generates JSON documentation of API endpoints.

```py
# in core/router.py
from rest_framework import routers

CiviWikiRouter = routers.DefaultRouter()
```
