### ISSUE TITLE
Move all account code from `api` to `accounts` app

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1031]
The `api` app contains code that should be moved to the `accounts` app. Move all of the following code to the `accounts` app, fix any related imports, and make migrations (if necessary).

- [x] [api/authentication.py](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/authentication.py) delete this file and follow [Django/DRF CSRF guidelines](https://www.django-rest-framework.org/topics/ajax-csrf-cors/#csrf-protection)
- [x] related code in `api/permissions.py` to `accounts/permissions.py`
    - [x] [`IsProfileOwnerOrReadOnly`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/permissions.py#L14)
    - [x] [`IsProfileOwnerOrDuringRegistrationOrReadOnly`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/permissions.py#L21)
- [x] related code in `api/read.py` -> `accounts/api.py`
    - [x] [`get_user`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L10)
    - [x] [`get_card`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L27)
    - [x] [`get_profile`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L50)
    - [x] [`get_feed`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/read.py#L109)
- [x] related code in `api/serializers.py` -> `accounts/serializers.py`
    - [x] [`ProfileCommonSerializer`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L11)
    - [x] [`ProfileSerializer`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L28)
    - [x] [`ProfileListSerializer`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/serializers.py#L95)
- [x] [accounts-related URL patterns](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/urls.py#L9) in `api/urls.py` -> `accounts/urls.py` 
    - [x] https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/api/urls.py#L17-L19
- [x] related code in `api/write.py` to `accounts/api.py`
    - [x] [`editUser`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/write.py#L308) - rename to `edit_user`)
    - [x] [`uploadProfileImage`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/write.py#L336) - rename to `upload_profile_image`
    - [x] [`clearProfileImage`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/write.py#L376) - rename to `clear_profile_image`
    - [x] [`requestFollow`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/write.py#L495) - rename to `request_follow`
    - [x] [ `requestUnfollow`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/write.py#L540) - rename to `request_unfollow`
    - [x] [`editUserCategories`](https://github.com/CiviWiki/OpenCiviWiki/blob/db319670f20d2e266db5814ed03f9209105365ef/project/api/write.py#L577) - rename to `edit_user_categories`

**Comment by gorkemarslan** [comment]
@brylie, I wanted to be assigned to be issue #1029. But I think this issue takes my attention more because right now I try to improve `accounts` app. I don't want to be too greedy so I am going to edit my post in that issue, and give my initial effort on `accounts` app. Its maintenance is more vital for us.

**Comment by brylie** [comment]
Agreed. Thanks, @gorkemarslan! I'll make the list of the remaining `accounts` code to be migrated, in this issue description.

**Comment by gorkemarslan** [comment]
I agree with most of your suggestions except for `related code in api/serializers.py -> accounts/api.py`. I think it would be more appropriate if we create the `accounts/serializers.py` file then move `api/serializers.py` to this file. Creating `serializers.py` is conventional and compatible with the single responsibility principle. We shouldn't give extra responsibility to `accounts/api.py` file. :)

I'm ok with the remaining. You did a great job when creating these subtasks and the ones in the other new issues. You really spent some time and effort. Awesome. :)

**Comment by brylie** [comment]
The `accounts/serializers.py` sounds fine. The list is mainly a guide so we won't omit any of the code.

**Comment by gorkemarslan** [comment]
Another point:

```
urlpatterns += [
    path('api/v1/account_data/<str:username>/', api.get_user, name="get_user"),
    path('api/v1/account_profile/<str:username>/', api.get_profile, name="get_profile"),
    path('api/v1/account_card/<str:username>/', api.get_card, name="get_card"),
    path('api/v1/feed/', api.get_feed, name="get_feed"),
    path('api/v1/edituser/', api.edit_user, name="edit_user"),
    path('api/v1/upload_profile/', api.upload_profile_image, name="upload_profile"),
    path('api/v1/clear_profile/', api.clear_profile_image, name="clear_profile"),
    path('api/v1/follow/', api.request_follow, name="follow_user"),
    path('api/v1/unfollow/', api.request_unfollow, name="unfollow_user"),
    path('api/v1/edit_user_categories/', api.edit_user_categories, name="edit_user_categories"),
]
```

It is worth to note that if we keep api-related urls in `accounts.urls.py`, we need to put 'api/v1/' prefixes for these type of URLs as I do above. We should create a separate folder for api-related URLs. Then we can add the prefix in `settings.urls` for this folder. `(path('api/v1/', include(urls.api)))`.

So our url folder can be like that:

```
urls                  -> parent directory
  |_ urls.py        -> our regular urls.py. A better name can be found
  |_ api.py         -> api-related urls
```

**Comment by brylie** [comment]
That suggestion sounds good. Will Django pick up the new `urls.py` automatically by being in the `urls` directory? Or will there be some necessary configuration? I'd like to stick close to Django/DRF conventions.

**Comment by gorkemarslan** [comment]
We've already had in our `core/urls.py`:

https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/core/urls.py#L30

It is enough to change this line to:
```
path("", include('accounts.urls.urls')),
path("api/v1/", include('accounts.urls.api')),
```

**Comment by brylie** [comment]
One issue is our API code will be spread across multiple apps, such as `accounts`, `threads`, and `categories`. So the change might be more along the lines of:

```py
path("", include('accounts.urls.urls')),
path("api/v1/accounts/", include('accounts.urls.api')),
```

**Comment by gorkemarslan** [comment]
That makes sense. :)

**Comment by gorkemarslan** [comment]
I have another question about ` CsrfExemptSessionAuthentication`. Since it might turn to be a discussion I don't want to ask it in the review part of the PR.

Should we use the default DRF authentication in the project? Which is:

```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}
```
 If it is, I think I should add @csrf_exempt decorators to post, put, etc HTTP methods.


I take a look at the code again:

https://github.com/CiviWiki/OpenCiviWiki/blob/28ba0b20531575cdf5036b703d3b2ff83cbf81ad/project/core/settings.py#L152-L166

We only use `CsrfExemptSessionAuthentication` in the debug mode.

**Comment by brylie** [comment]
Yes, I'd like to deprecate any custom authentication code and use DRF defaults.

**Comment by gorkemarslan** [comment]
I edit my last post to add a new part to the below. Please look at it, as well.

Why do we use api in this project? In the future, are we planning to use Vue.js or React.js as a frontend?

I mean are we using api endpoints anywhere in the project? Or we have a purpose of serving our applications to users who want to use our API?

**Edit:**
I found the usage in the project:
https://github.com/CiviWiki/OpenCiviWiki/blob/d5e7ee2f9424b5877b9e9ef02fe9b6b4826d1c4c/project/threads/templates/static/js/user-setup.js#L12

I am asking the questions above because. I try to understand we need to add `JWT Token` as` DRF authentication` in the project.

**Comment by brylie** [comment]
> Why do we use api in this project? In the future, are we planning to use Vue.js or React.js as a frontend?

No plans to add Vue or React. We are moving _away_ from having an SPA frontend, which was previously made with Backbone.js. The SPA paradigm isn't a good fit for this project, as it has added too much maintenance overhead. #827 

Also, there are some re-emerging approaches, such as [HTMX](https://htmx.org/), to get dynamic functionality for _parts_ of the page/app that need it without throwing away the server-rendering parts of the Django web framework.

**Comment by gorkemarslan** [comment]
Ok, thanks for your response. I will update my PR in a couple of hours. To work on another issue in the weekend, I want to be assigned to another issue? Which one do you suggest? Maybe one related to the general router?

**Comment by brylie** [comment]
> I mean are we using api endpoints anywhere in the project? Or we have a purpose of serving our applications to users who want to use our API?

For the 2.0 milestone, I am just proposing we _refactor_ the code and keep the API more-or-less unchanged, although we don't have an actual deployment so changing URL structure is permissible.

The 2.0 milestone will include tasks to port the JavaScript (Backbone.js) templates over to conventional Django templates, such as epic #889.

In the long run, keeping the API would make it possible for external developers to integrate with CiviWiki so it seems worthwhile to keep around. We just don't have the resources to commit to anything like "API-first" development or the SPA paradigm.

**Comment by gorkemarslan** [comment]
At that time, you can assign me to add `JWT Token` to the project for the `3.0 milestone`. :smile:

**Comment by gorkemarslan** [comment]
> That suggestion sounds good. Will Django pick up the new `urls.py` automatically by being in the `urls` directory? Or will there be some necessary configuration? I'd like to stick close to Django/DRF conventions.

@brylie, I want to give a clear answer to your question: 

When creating a new Django project, the Django automatically specifies where URLs are stored in the project:
https://github.com/CiviWiki/OpenCiviWiki/blob/cbf3ee5dee481d2e9223374471351f1e43a68717/project/core/settings.py#L57

It is not relevant to our project but if we want to move the root `urls.py` to somewhere else apart from where it is initially located, we have to tell its new place the Django in the `settings.py`. Otherwise, it won't know.

Or if we want to create a new `urls` directory inside `core` app and move urls.py into it, we should specify it in the `settings.py` like that:
` ROOT_URLCONF = "core.urls.urls" `


Further, app-level urls.py files are not compulsory but recommended. We can put all of them to root `urls.py` without creating `<app.urls.py>` but it is not the best practice and is against the modularity principle.

Django never collects the location of app-level `urls.py` files automatically. Instead, we specify their locations with [include](https://docs.djangoproject.com/en/3.2/ref/urls/#include) function inside root level `urls.py `file.:
https://github.com/CiviWiki/OpenCiviWiki/blob/cbf3ee5dee481d2e9223374471351f1e43a68717/project/core/urls.py#L30-L31

I hope you find this useful.
