### ISSUE TITLE
Restructuring App URLs for Django 3.2

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1069]
### Idea summary

Restructures the app's Urls according to non-deprecated methods

### Further details

The urls in threads and core use the deprecated method
```py
url(r'<path>')
```
which should be migrated to path method according to django 3.2 documentation.
The tasks are as follows
- [ ] Migrate Core urls to path
- [ ] Migrate threads urls to path
- [ ] Migrate frontend_views to path

**Comment by gorkemarslan** [comment]
@AbhijithGanesh, The main purpose of #1066 is exactly this. :) So I will remove this one and #1071. I'll add your text above to the issue #1066. 
Since `hacktoberfest` has started, new contributors have come to the new issues labeled by `hactoberfest`. So we need to be careful when we open new issues. New issues should include clear guidelines.

**Comment by AbhijithGanesh** [comment]
Can I  edit this issue you've created and add tasks there or add it in my issue ? @gorkemarslan

**Comment by AbhijithGanesh** [comment]
Closing this as we'd be moving to #1066

**Comment by gorkemarslan** [comment]
We should add new tasks to the parent issue. You can get started with improving the issue you're assigned.
