### ISSUE TITLE
Removal of AWS config

### ISSUE THREAD

**Issue by AbhijithGanesh** [CiviWiki/OpenCiviWiki#1165]
### Description

I think we don't use AWS anymore so we can remove the AWS related configuration right? @brylie 

Remove the following lines:
https://github.com/CiviWiki/OpenCiviWiki/blob/79b13e81b6e3524b70196c40ef73a28c8045c30a/project/core/settings.py#L98

https://github.com/CiviWiki/OpenCiviWiki/blob/79b13e81b6e3524b70196c40ef73a28c8045c30a/project/core/settings.py#L101-L107

**Comment by brylie** [comment]
@AbhijithGanesh, sure. Would you mind adding a list of the specific file(s) to this issue description to help out any developer who takes the task?

**Comment by khushkaushal** [comment]
Hi, I would like to contribute to this issue. I have my dev environment setup and read the contribution guide. Is there anything else I need to do?

**Comment by brylie** [comment]
Thanks, @khushkaushal. We are still waiting for @AbhijithGanesh to list which specific files they propose to be removed.

**Comment by AbhijithGanesh** [comment]
I reckon it's only  the settings file which configures AWS. One other file uses [project/core/templates/email/base_email_templates.html](https://github.com/CiviWiki/OpenCiviWiki/blob/develop/project/core/templates/email/base_email_template.html) but that file uses it for static loading so it needn't be removed.

**Comment by khushkaushal** [comment]
Yep, that's what I got from a quick search in vs code.

**Comment by AbhijithGanesh** [comment]
Great then, would you like to patch this ? @khushkaushal

**Comment by khushkaushal** [comment]
@AbhijithGanesh yep. sure thing! How do i take the ticket?

**Comment by AbhijithGanesh** [comment]
One of the maintainers has to assign it to you but you can create a PR meanwhile, I am sure this isn't a major PR

**Comment by khushkaushal** [comment]
okay sounds good thanks!

**Comment by gorkemarslan** [comment]
@khushkaushal, I'm assigning you to this issue. Please don't hesitate to ask anything.

**Comment by khushkaushal** [comment]
@gorkemarslan I am trying to push my branch to the repo but it says that i don't have permissions. Do i need to be granted permissions?

` project git:(remove-aws-config)  git push --set-upstream origin remove-aws-config
ERROR: Permission to CiviWiki/OpenCiviWiki.git denied to khushkaushal.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights`

**Comment by gorkemarslan** [comment]
@khushkaushal, the problem is not related to the project repository. In fact, this error is caused by your local Git settings.
To be clear, everyone can contribute to this project without getting permission. We're welcome to everyone. :)

Could you look at this [blog post](https://careerkarma.com/blog/git-fatal-could-not-read-from-remote-repository/) and these [SO answers](https://stackoverflow.com/questions/13509293/git-fatal-could-not-read-from-remote-repository)? My initial guess, you might not set up ssh_key for GitHub properly. 

The solution should not be too complicated, please prefer simple ones. If the links won't help you, could you inform us? Then we can look through another way to solve it.

**Comment by AbhijithGanesh** [comment]
@khushkaushal you need to fork the repository and push it to that repo, not to OpenCiviWiki directly.

**Comment by khushkaushal** [comment]
Thanks @AbhijithGanesh . Forking worked.
