### ISSUE TITLE
Remove REST endpoints from project

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#1304]
### Idea summary

Remove all REST endpoints and the Django REST framework from the project

### Further details

We need to simplify this project architecture. The original decision to split the code into backend and frontend projects proved to be unsustainable.

## Task
- [ ] all REST endpoint code should be removed from project
- [ ] all REST dependencies (e.g. Django REST Framework and CORS headers) should be removed from project

**Comment by HuangLiPang** [comment]
Hello @brylie,

I think I can work on this.
For the rest endpoint, do you mean all the `view` and `viewset` of the `rest_framework` and all api.py and url.py files?

**Comment by brylie** [comment]
Yes, but only the urls and views that are serving JSON.

**Comment by HuangLiPang** [comment]
@brylie Got it. Can I take this?

**Comment by brylie** [comment]
Thanks. I've assigned you

**Comment by gorkemarslan** [comment]
@brylie, further investigation is needed for this task because the front end partially uses REST. If we remove REST endpoints and views from the project we will lose track of the whole logic of these parts. (Of course, they are accessible via git) Right now, the front end does not work as expected. I feel like things will be more complicated if we just remove REST. So we should migrate Django rest framework implementations to Django. Then we can remove REST.

**Comment by HuangLiPang** [comment]
@gorkemarslan Thanks for your clarification. So should I migrate drf to Django first?

**Comment by brylie** [comment]
OK, let's put this task on hold while we develop a specific migration roadmap. Right now, the roadmap is huge and ill-defined.
