### ISSUE TITLE
No button to exit edit profile screen

### ISSUE THREAD

**Issue by mdwest** [CiviWiki/OpenCiviWiki#211]
We need an "x" button to close the edit profile pop out

![image](https://user-images.githubusercontent.com/30572202/43048657-1b590398-8da0-11e8-9fc0-d857e2f3b7ac.png)

**Comment by AT1452** [comment]
I'm available to take this issue if that's alright?

**Comment by GokuMizuno** [comment]
You will get no objections from me.


Sent from my Sprint Phone.-------- Original message --------From: AT1452 <notifications@github.com> Date: 7/23/2018  13:13  (GMT-05:00) To: CiviWiki/OpenCiviWiki <OpenCiviWiki@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [CiviWiki/OpenCiviWiki] No button to exit edit profile screen
  (#211) 
I'm available to take this issue if that's alright?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CiviWiki/OpenCiviWiki","title":"CiviWiki/OpenCiviWiki","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/CiviWiki/OpenCiviWiki"}},"updates":{"snippets":[{"icon":"PERSON","message":"@AT1452 in #211: I'm available to take this issue if that's alright?"}],"action":{"name":"View Issue","url":"https://github.com/CiviWiki/OpenCiviWiki/issues/211#issuecomment-407132792"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CiviWiki/OpenCiviWiki/issues/211#issuecomment-407132792",
"url": "https://github.com/CiviWiki/OpenCiviWiki/issues/211#issuecomment-407132792",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [CiviWiki/OpenCiviWiki] No button to exit edit profile screen (#211)",
"sections": [
{
"text": "",
"activityTitle": "**AT1452**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@AT1452",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"CiviWiki/OpenCiviWiki\",\n\"issueId\": 211,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"CiviWiki/OpenCiviWiki\",\n\"issueId\": 211\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/CiviWiki/OpenCiviWiki/issues/211#issuecomment-407132792"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 359161151\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by mdwest** [comment]
@AT1452 That would be great! Thank you!
When you push your code please link @jl24 to review.

**Comment by jmarkham828** [comment]
Hello, I noticed this issue has not been marked as closed or completed. Could I maybe take a look at it?

**Comment by brylie** [comment]
@jmarkham828 that would be great, thanks! How can we help you along your way? Do you have a development environment already?

**Comment by dacdao1** [comment]
Hi, I saw this issue with your project, and it is still open. I just wanted to know if I could work on this issue for you? Thank you.

**Comment by brylie** [comment]
@dacdao1 yes, this issue is open. Thanks for your offer. How can we help you get started?

**Comment by dacdao1** [comment]
As of right now, no not really. I will download the development environment with docker and I will message you if I have any problem.

**Comment by dacdao1** [comment]
@brylie I'm setting up the docker development environment and it seems that it is not set up correctly for me. Should I set up using the "local setup" way? Also which file is the "edit profile" HTML page located? I look all over the webapp folder and frontend_views and I can't find that page. Thank you.

**Comment by brylie** [comment]
@dacdao1 we are trying out the Docker approach as a recommendation for new devs. What problem(s) did you encounter? Was there anything missing from the docs? @TomaszKolek may be able to help you work through the Docker set-up, and add missing documentation.

The "Edit Profile" dialogue can be found in [/webapp/templates/partials/account/account_settings.html](https://github.com/CiviWiki/OpenCiviWiki/blob/dev/project/webapp/templates/partials/account/account_settings.html)

**Comment by dacdao1** [comment]
Ok, perfect @brylie. Now I know where that pop up is located.

@TomaszKolek I was following along the setup guide at https://github.com/CiviWiki/OpenCiviWiki/blob/dev/readmes/docker-setup.md. 
Once I got to the "docker-compose up" command, my command line went fine through redis and everything else that needed to be set up, but once it gets to the DB, it said that I need the root file or folder of "/data". Can you tell me what is the workaround on that problem or should I set up with the local setup way? Thank you for your help.

**Comment by brylie** [comment]
Definitely try to work through the Docker setup. It will likely be easier than the local setup, and will probably be our recommendation going forward.

**Comment by Sparrow1029** [comment]
Hey there, I also have been trying to get through the Docker setup, and when civiwiki-backend is attempting to start (after running `docker-compose up`), after initializing ChromeDriver it runs into `ImportError: cannot import name Account` from the django models.
Even when I spin up another terminal and enter the civiwiki-backend image shell, running `python manage.py` commands recommended to populate database spits the same error.
I attached the stack trace... any help would be welcome, because I'd love to contribute--it's a great project :)
[stackTrace.txt](https://github.com/CiviWiki/OpenCiviWiki/files/2988636/stackTrace.txt)

**Comment by brylie** [comment]
OK, not sure why it is initializing ChromeDriver, for one.

What branch are you working on?

**Comment by brylie** [comment]
@TomaszKolek would you help diagnose the error? Is this a recent bug?

**Comment by Sparrow1029** [comment]
@brylie Hi! Sorry for the delayed reply. I cloned the repo and I'm on the `dev` branch. I played with the module import references a little to see if I could fix the error (i.e: changed `models` to `.models` etc), which didn't work so I put them back to their original state, and the error was still there.
I'm not great with Docker yet, and I think I need to fork the repo rather than cloning...

**Comment by brylie** [comment]
It looks like the Dockerfile is using Python 2.7:
https://github.com/CiviWiki/OpenCiviWiki/blob/dev/Dockerfile#L1

**Comment by brylie** [comment]
I have pinged @TomaszKolek via Upwork, to see if he can help out here. I am stumped as to why the modules aren't loading correctly. Sorry for the lack of help on this one.

**Comment by TomaszKolek** [comment]
Yeah I see imports are buggy, let me fix them

**Comment by TomaszKolek** [comment]
@Sparrow1029 let's try now (please update dev branch)

**Comment by dacdao1** [comment]
@Sparrow1029 are you going to work on this issue?

**Comment by brylie** [comment]
@dacdao1 pkease consider taking this issue:
https://github.com/CiviWiki/OpenCiviWiki/issues/231

**Comment by Sparrow1029** [comment]
Hey, that change to the imports worked! Thanks @TomaszKolek  :) And yes, I can try to work on this issue if @dacdao1 doesn't want it

**Comment by brylie** [comment]
Either this or #231 would be great. #231 is a 'show stopper' on Firefox.

By the way @dacdao1 and @Sparrow1029, please consider joining our Matrix chatroom:
https://riot.im/app/#/room/#CiviWiki:matrix.org

**Comment by dacdao1** [comment]
Hey @Sparrow1029 I will work on that #231 issue. And how did you get docker to work by the way. Just do the normal docker setup?

**Comment by Sparrow1029** [comment]
@dacdao1 Yes, but after my first few attempts: I cleaned all of the docker images from the first time around, re-cloned and updated, then when Tomas fixed the circular import issue, the civiwiki_backend docker server started working as expected

**Comment by brylie** [comment]
@Sparrow1029 how are you progressing on this issue? How can we be of assistance to help you complete the task?

**Comment by danielgrijalva** [comment]
Hi! I can take on this issue if nobody is working on it :sweat_smile:

**Comment by Sparrow1029** [comment]
Hi there! I never got the environment running, and classes/moving have gotten in the way, feel free to take it @danielgrijalva! Apologies, and hopefully when I get settled down in the new place I will have time to set up the environment and contribute.

**Comment by danielgrijalva** [comment]
Hey I just realized, the profile "pop out" mentioned is **_not_** a pop out, it's a navigation component with _tabs_. So... it doesn't make sense to add the "x" button to close the edit section, right? I mean, to "close" it, the user should just click on another section, right?

My suggestion would be to remove the styles from the edit button (background color, shadow, :hover), to make the tabs more evident.

@mdwest @brylie

**Comment by mdwest** [comment]
@danielgrijalva Good Point, I think it would make better sense if the edit profile tab looked like the rest of the tabs. No need for an exit button.

**Comment by danielgrijalva** [comment]
Hi @brylie @mdwest I think this issue should be closed now :sweat_smile:
