### ISSUE TITLE
Arbitrarily picks location

### ISSUE THREAD

**Issue by Shreyas4991** [CiviWiki/OpenCiviWiki#229]
I attempted to pick a location outside the United States. During registration I first let the google maps location picker find me. Then before proceeding further I edited the address to a single continent name. The address on my profile however shows my city from the Map and a random US State.

**Comment by brylie** [comment]
Thanks for the bug report! We can prioritize this in an upcoming sprint.

**Comment by Shreyas94** [comment]
I think I might have an idea about why the state was picked seemingly randomly. The map picked in a state outside the US which shares the abbreviation TN. So it put me in Tennessee. Why it retained that information after I edited the address completely still remains a question. Does it mean that once the map picks an address, it can't truly be edited in the input box? Since the website appears to be focused on the United States at the moment, it might be a good idea to have a compulsory ZIP code input which I guess would be verifiable and a good way to determine one's constituency.

**Comment by richifuentes** [comment]
Hi @brylie I would like to start contributing to this project and give it a go with this issue. I have tried to setup the development environment but I have got some errors on docker, see below

WARNING: Image for service backend was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating civiwiki-db    ... done
Creating civiwiki-redis ... done
Creating civiwiki-backend ... error

ERROR: for civiwiki-backend  Cannot start service backend: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/app/entrypoint.sh\": stat /app/entrypoint.sh: no such file or directory": unknown

ERROR: for backend  Cannot start service backend: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/app/entrypoint.sh\": stat /app/entrypoint.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.

any ideas?

**Comment by brylie** [comment]
What happens when you run `docker-compose build`?

**Comment by richifuentes** [comment]
I did run `docker-compose build` successfully then I have tried `docker-compose up` but I am getting always these errors from db and backend in loop:

civiwiki-db | FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
civiwiki-db | HINT:  The server must be started by the user that owns the data directory.

civiwiki-backend | standard_init_linux.go:207: exec user process caused "no such file or directory"

Any ideas?

**Comment by richifuentes** [comment]
I have set up the environment finally on my Mac, Docker seems to work better on Mac than on Windows.
@brylie: so now I am sorted with the development environment, what is the desired change for this issue? and can you please guide me to which files should I start looking for?

**Comment by brylie** [comment]
Well, I think we should discuss how to handle users outside of the U.S., as there isn't an obvious answer. What are your thoughts @richifuentes?

**Comment by richifuentes** [comment]
The first time I have had a look at OpenCiviWiki it looks to me to be an App just for US Citizens, by the way it is structured and the language used. Then is for the Business (however wrote the requirements) to decide if this App could/should be used globally then I think for the Address a complete form should be implemented where users would enter Street Name and Number, Zip Code, Province/State, Country, etc. and only then we can check how the address was submitted and give feedback to the user if necessary. Also, the google maps locate function could be used to help the users with the form.

**Comment by brylie** [comment]
Yes, we will keep it U.S.-centric for now, since there isn't currently functionality for other addresses, governments, legislation, etc.

How do you propose we improve the location selection?

**Comment by richifuentes** [comment]
Hi @brylie , we first need to fix a small typo that is causing the application to just show the purple screen instead of the login window, I have noticed that since the last commit a couple of days ago this error started happening, see here:
![image](https://user-images.githubusercontent.com/9931749/57300507-3cb0a580-70d7-11e9-9ec9-7a72e171aa46.png)
the user-setup.js file needs to be corrected on line 260. From this:
![image](https://user-images.githubusercontent.com/9931749/57300584-6964bd00-70d7-11e9-90eb-8da1513a1b4b.png)
To this:
![image](https://user-images.githubusercontent.com/9931749/57300651-8f8a5d00-70d7-11e9-88ec-b78a614442b6.png)
Regards,
Ricardo

**Comment by richifuentes** [comment]
An issue that I have with the development environment for this ticket:  is there a way to setup https on the docker deployment? I cannot test the locate function without https, all the browsers block it, so whatever Address I have entered there does not get geolocated and so I cannot troubleshoot the process of checking the addresses, any ideas?
![image](https://user-images.githubusercontent.com/9931749/57315197-65df2f00-70f3-11e9-91f9-f88528e6b13d.png)

**Comment by brylie** [comment]
@richifuentes can you open a PR to fix the JavaScript error?

**Comment by brylie** [comment]
@TomaszKolek can you clarify how @richifuentes can access the CiviWiki Docker via HTTPS?

**Comment by brylie** [comment]
@all-contributors please add @Shreyas4991 for bug

**Comment by brylie** [comment]
@all-contributors please add @richifuentes for question, ideas, bug

**Comment by torabshaikh** [comment]
@brylie Does this issue still exist? I am trying to find a project for my first open source contribution. Please let me know if this issue is fixed or some other issue in which I can contribute. Thanks

**Comment by brylie** [comment]
@torabshaikh this may be resolved now. Would you like to try another issue?

**Comment by torabshaikh** [comment]
@brylie Yeah. Very much.

**Comment by brylie** [comment]
@torabshaikh how about this issue:
https://github.com/CiviWiki/OpenCiviWiki/issues/210

**Comment by torabshaikh** [comment]
@brylie Yes. This looks good.

**Comment by richifuentes** [comment]
> @TomaszKolek can you clarify how @richifuentes can access the CiviWiki Docker via HTTPS?

Hi Thomas, I have never got the instructions on how to setup CiviWiki Docker via https, this is important to test locate scripts and other features, without https all browsers blocked location automatically.

**Comment by brylie** [comment]
@richifuentes please open a new ticket for this HTTPS issue.
