### ISSUE TITLE
"Representative has no field named 'first_name'" - error when running "loaddata data/congress.json"

### ISSUE THREAD

**Issue by wjkpowell** [CiviWiki/OpenCiviWiki#542]
When running the following command:

>python project/manage.py loaddata data/congress.json

I get this error:

`Problem installing fixture '/app/data/congress.json': Representative has no field named 'first_name'`

I'm on a Mac running Mojave 10.14.5
Using the Docker setup

I will work on creating a video with a fresh `git clone` now.

**Comment by brylie** [comment]
Thanks for the error report @wjkpowell

**Comment by wjkpowell** [comment]
Here's a link to the video where I reproduce this problem:

https://youtu.be/eDbxi3VhL2A

**Comment by umr55766** [comment]
Hey @brylie ,

I am interested in picking this up.

I have investigated this issue and found that current `representative` model doesn't have `first_name` and `last_name` as separate fields anymore.

In this commit https://github.com/CiviWiki/OpenCiviWiki/commit/6d39b4c8dd1ae504ed3d861834fc67f9f8007ff9 `first_name` was renamed to `name` and `last_name` field was dropped.

So now we need to figure out that how do we keep `data/congress.json` in sync with these model changes?

One solution that's coming to me is, we can remove `first_name` & `last_name` and merge their value as a new field named `name` in the `data/congress.json` file itself, so that it remains in sync with the `representative` model.

Open to hear your thoughts.

**Comment by brylie** [comment]
@umr55766 that sounds good. Please start a new branch and open a pull request with your suggestions.

**Comment by umr55766** [comment]
@brylie Thank you.

I tried making the change. But the issue is there are few other outdated fields too.

|Model Field|Field in JSON|
|---|---|
|name|official_full_name|
|district|district|
||senate_class|
|bioguide_id|bioguideID|
|state|state|
|   |about_me|
|start_date|term_start|
|party|party|
|end_date|term_end|
|   |level|

1. Can/Should we use `official_full_name` field as `name` attribute ?
2. What to do with `senate_class`, `about_me` & `level` data in JSON file ?
3. Can you please have a look at the mapping I have indicated in above table and let me know your thoughts.

**Comment by brylie** [comment]
To the extent possible, we should try to align with the data in the file. If there are fields we don't want to store, such as `about_me`, lets just ignore or drop them.
