### ISSUE TITLE
The image in README is not loading. The website is unreachable

### ISSUE THREAD

**Issue by virejdasani** [CiviWiki/OpenCiviWiki#770]
The image in README is not loading. The website is unreachable,
Download that image from the website and store it in a folder in this repo. This way, you can reference the image in the README.md in this repo instead of linking to another website.
I would make a fork and do this myself but I don't know what image it is since it does not load

**Comment by pprasha** [comment]
Please sign this issue to me.

**Comment by virejdasani** [comment]
How do I do that? I'm new to this

**Comment by pprasha** [comment]
I don't think you can but an member can I am pretty sure.

**Comment by BrianPainter** [comment]
Are you referencing the second badge at the top of the readme file? I believe that is taken care of in pull request #777

**Comment by pprasha** [comment]
oh okay thanks for letting me know

**Comment by ganeshbhargav** [comment]
I think it is better to link all images from a folder in Google Drive/Onedrive/any other cloud instead of hyperlinking to website.
It would solve the unreachability problem for now and not create any more in future.

These are links i created for these images :-
https://img.shields.io/badge/ComVer-compliant-brightgreen.svg - https://drive.google.com/file/d/1ZBMacB6h6cknOoBXiTx03H7amjYsVH61/view?usp=sharing
https://api.codeclimate.com/v1/badges/5241b4275cc2dffe90f2/maintainability - https://drive.google.com/file/d/10wxDuF4BXOA5UTwCBPs68Cje5IdwWKEe/view?usp=sharing

Hope it helps !
