### ISSUE TITLE
Reorganize project structure (incrementally)

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#78]
As discussed with @jl24, the project sourcecode is somewhat disorganized. The backend code doesn't really follow conventional Django packaging approach, and the frontend is substantially more disorganized.

# Goal
Improve project organization. Have cohesive organization between client and server code.

# Sub-tasks
- [ ] Refactor frontend #82
- [ ] Refactor backend #83

**Comment by jl24** [comment]
As far as the frontend code goes, with the javascript files, I like the idea of going with the modular approach, where instead of being organized by individual views, being organized to reflect the structure of the application api. This new structure will probably move us towards the incorporation of a js bundler (e.g. webpack). The LESS files will move into a similar component-based structure as well, and allow us to take advantage of minification

**Comment by brylie** [comment]
@jl24 lets break this task into two parts:

- frontend refactor
- backend refactor

I can create the issues. Would you like to spearhead the frontend while I coordinate the backend refactor?
