### ISSUE TITLE
Document deployment instructions for Heroku (development, testing, production)

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#98]
Add deployment instructions to our CONTRIBUTING.md regarding how to deploy testing instances to Heroku. Note: do not publish sensitive information, such as Heroku keys.

# Task
- [ ] Documentation exists explaining how to deploy testing releases to *production*, *dev*, and *staging*

**Comment by jl24** [comment]
Heroku requires the Procfile for deploying the app to be in the root folder. Two possible solutions: 

1. Move the Main heroku procfile to the root directory 
I'm not really a fan of this because it disrupts our project structure
2. Create a subtree of dev (or whichever development branch that is being deployed), the `project` directory, that is only used for deploying to the heroku environment.
