### ISSUE TITLE
Sunlight API deprecated 

### ISSUE THREAD

**Issue by JOO33** [CiviWiki/OpenCiviWiki#99]
## Closure of Sunlight Labs
The sunlight foundation has ended their online services and thus dropped support for their api. All references to the api must be changed accordingly.

## Replacing the Sunlight API

The Sunlight Congress API should be replaced with the [ProPublica Congress API](https://www.propublica.org/datastore/api/propublica-congress-api) in conjunction with [OpenStates API](https://docs.openstates.org/en/latest/api/v2/) for location-based services
 
Notes:
- Developers now need to get API keys from each of those two services. The project documentation and the settings variables should change to include those. 
- The `sunlight` python module should be removed
- ProPublica Congress API does not provide an official python package and thus we will have to develop our own module, perhaps through the to-be empty local `legislation` module

## Architecture
The deliverable for this task consists of API endpoints (using DRF) that wrap endpoints on the third party APIs. This is to allow CiviWiki clients to query the third party APIs without requiring the client to have an API key or exposing the CiviWiki internal key.

The initial endpoints should be minimal, and allow searching by location or keyword.

## UX
When adding or editing a Civi, a user will be able to do a search, e.g. a few letters or a keyword. The search will return results from the remote service, via our backend. A user can then select a result, and link it to the Civi.

## Screenshot
The Civi can be seen in the far right column of this screenshot:
![screenshot from 2019-02-21 20-13-21](https://user-images.githubusercontent.com/17307/53191745-4a48aa00-3615-11e9-961f-f9c98f1a6d3d.png)

**Comment by TomaszKolek** [comment]
@brylie I see Links field shows currently existing problems. Should we display bills from API in links field together with problems or rather make it as a second field like `Linked bills`

**Comment by brylie** [comment]
Make a second field with a similar style to Linked bills field. The linked bills field is just an example to follow.

**Comment by brylie** [comment]
@TomaszKolek can we close this issue?

**Comment by brylie** [comment]
I.e. this is the *last* issue remaining for the 1.0 release.

**Comment by pscheid2** [comment]
Is it critical to have the propublica integration functioning in this milestone 2.0?

I don't see this as a core feature of the civiwiki site, so I'm thinking we remove this from milestone 2.0 and maybe even close this issue until it becomes a priority.

**Comment by brylie** [comment]
@pscheid2 we actually have tasks to remove all code related to elected representatives and bills from CiviWiki as part of the 2.0 milestone.

- #830 - remove features related to elected representatives
- #857 - remove features related to legislation

The elected representatives and legislation features added considerable complexity to CiviWiki, while extending it beyond its core value of promoting constructive discourse around social issues. The elected representatives and legislation features also limited the scope of relevancy of the CiviWiki project, since they were centered around U.S. political system.

This issue is basically now complete, in so far as we no longer plan to support features related to legislation. We just need to make sure all related code has been cleaned up.

**Comment by pscheid2** [comment]
Great! Given that we have other issues open to remove code related to representatives and bills, we should be able to close this issue.

**Comment by brylie** [comment]
Closing, as agreed with @pscheid2
